//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntityProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCVENTİTYEntities : DbContext
    {
        public DBCVENTİTYEntities()
            : base("name=DBCVENTİTYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLADRE> TBLADRES { get; set; }
        public virtual DbSet<TBLCALİSMALARİM> TBLCALİSMALARİM { get; set; }
        public virtual DbSet<TBLHAKKIMDA> TBLHAKKIMDAs { get; set; }
        public virtual DbSet<TBLİLETİSİM> TBLİLETİSİM { get; set; }
        public virtual DbSet<TBLYETENEKLER> TBLYETENEKLERs { get; set; }
    }
}
